<?php

class Images
{
	//Image properties:
		#Name
		#Description
		#Size
		#Dimensions
		#is it a backup?
		#has it a backup?
		#
		#Generated by api?
	
	public function FetchAllImages()
	{
		//Pseudocode
		$sqlCommand = "Fetch all images";
		
		//Send to mysql class
		//get results as an array
		//return array (with information?)
	}
	
	public function GetImageInfo()
	{
		//pseudocode
		$sqlCommand = "Get the information";
		
		//send to mysql class
		//get results
		//return array (associative?)
	}
	
	public function UploadImage()
	{
		//pseudocode
		$sqlCommand = "upload image";
		
		//Maybe pause this function and send to different function first?
		//Maybe not pause but use this function when the user confirms the upload
		
		// - place image in a temporary folder
		// - scan image and show information
		// - enhancement possibilities?
		// - something more before finally uploading image
		
		//When user wants to upload
		//send to mysql class to upload
		//get information on success or failure
		
		//remove image from temporary location ONLY when success is ensured
	}
	
	public function BeforeUpload()
	{
		//Here we can scan the image and do all sorts of stuff before sending it to be uploaded
		//See UploadImage function for more
		
		//When the user selects to confirm the upload, move on to UploadImage()
	}
	
	public function EditImage()
	{
		// - Edit name
		// - Edit description
		// - Crop?
		// - Enhance?
	}
}



?>